# script para associar todas as categorias aos conceitos que faltam

import json

# Carregar o glossário
with open('glossario_juncao.json', 'r', encoding='utf-8') as f:
    glossario = json.load(f)

# Cole aqui a sua lista de tuplos (conceito, categoria)
lista = [
 ('abeta', 'Genética e Biologia Molecular'),
 ('ACA', 'Imunologia'),
 ('acalabrutinib', 'Fármacos e Terapias'),
 ('acidente vascular cerebral isquêmico', 'Doenças'),
 ('acidose metilmalônica', 'Doenças'),
 ('Ad5-nCoV', 'Vacinas e Imunização'),
 ('adequació de les actuacions sanitàries', 'Profissionais e Serviços de Saúde'),
 ('adequació de l’esforç terapèutic', 'Profissionais e Serviços de Saúde'),
 ('ADG20', 'Fármacos e Terapias'),
 ('adjuvante genético', 'Genética e Biologia Molecular'),
 ('ADN', 'Genética e Biologia Molecular'),
 ('aerosol', 'Equipamentos e Dispositivos'),
 ('agent biològic', 'Microbiologia e Virologia'),
 ('agrupament', 'Epidemiologia e Saúde Pública'),
 ('agèusia', 'Sintomas e Sinais'),
 ('alergia asmática', 'Doenças'),
 ('alfa-tocoferol', 'Substâncias Químicas'),
 ('alta', 'Termos Gerais'),
 ('alta mèdica', 'Termos Gerais'),
 ('alumã', 'Substâncias Químicas'),
 ('alunacedasa alfa', 'Fármacos e Terapias'),
 ('ambroxol', 'Fármacos e Terapias'),
 ('amiloidose sistêmica senil', 'Doenças'),
 ('AMY-101', 'Fármacos e Terapias'),
 ('anakinra', 'Fármacos e Terapias'),
 ('analgèsic', 'Fármacos e Terapias'),
 ('angina instável', 'Doenças'),
 ('angiografia de retina', 'Diagnóstico'),
 ('ansietat anticipatòria', 'Psicologia e Psiquiatria'),
 ('antibiòtic', 'Fármacos e Terapias'),
 ('anticòs', 'Imunologia'),
 ('antigen', 'Imunologia'),
 ('antimonial pentavalente', 'Fármacos e Terapias'),
 ('antipirètic', 'Fármacos e Terapias'),
 ('antiretroviral', 'Fármacos e Terapias'),
 ('antiviral', 'Fármacos e Terapias'),
 ('antivíric', 'Fármacos e Terapias'),
 ('antiàlgic', 'Fármacos e Terapias'),
 ('análise biomecânica', 'Diagnóstico'),
 ('anòsmia', 'Sintomas e Sinais'),
 ('apicoplasto', 'Anatomia'),
 ('aplimod', 'Fármacos e Terapias'),
 ('aplanar la corba', 'Epidemiologia e Saúde Pública'),
 ('apoptose', 'Biologia Molecular'),
 ('apremilast', 'Fármacos e Terapias'),
 ('araraquara', 'Vírus'),
 ('ARN missatger', 'Genética e Biologia Molecular'),
 ('ARNm', 'Genética e Biologia Molecular'),
 ('arrítmia', 'Doenças'),
 ('artrodistrator', 'Procedimentos Médicos'),
 ('ARV', 'Fármacos e Terapias'),
 ('ASC09F', 'Fármacos e Terapias'),
 ('asimptomàtic -a', 'Sintomas e Sinais'),
 ('assaig aleatoritzat', 'Pesquisa Clínica'),
 ('assaig amb cegament', 'Pesquisa Clínica'),
 ('assaig amb cegament doble', 'Pesquisa Clínica'),
 ('assaig amb cegament triple', 'Pesquisa Clínica'),
 ('assaig clínic', 'Pesquisa Clínica'),
 ('assaig clínic aleatoritzat', 'Pesquisa Clínica'),
 ('assaig comunitari', 'Pesquisa Clínica'),
 ('assaig d’intervenció comunitària', 'Pesquisa Clínica'),
 ('astemizol', 'Fármacos e Terapias'),
 ('astènia', 'Sintomas e Sinais'),
 ('atenció al dol', 'Profissionais e Serviços de Saúde'),
 ('atenció domiciliària', 'Profissionais e Serviços de Saúde'),
 ('atenció hospitalària', 'Profissionais e Serviços de Saúde'),
 ('atenció primària', 'Profissionais e Serviços de Saúde'),
 ('atibuclimab', 'Fármacos e Terapias'),
 ('atrofia espinhal progressiva tardia', 'Doenças'),
 ('ATYR1923', 'Fármacos e Terapias'),
 ('autoinflamació', 'Doenças'),
 ('automostra', 'Diagnóstico'),
 ('autoritat sanitària', 'Profissionais e Serviços de Saúde'),
 ('aviptadil', 'Fármacos e Terapias'),
 ('avium', 'Microbiologia e Virologia'),
 ('azitromicina', 'Fármacos e Terapias'),
 ('acão vasoconstritora', 'Fisiologia'),
 ('aïllament', 'Epidemiologia e Saúde Pública'),
 ('aïllat', 'Microbiologia e Virologia'),
 ('aïllat víric', 'Microbiologia e Virologia'),
 ('bacilo de koch', 'Microbiologia e Virologia'),
 ('baciloscopia', 'Diagnóstico'),
 ('bactéria entero-hemorrágica', 'Microbiologia e Virologia'),
 ('bainha de mielina', 'Anatomia'),
 ('bamlanivimab', 'Fármacos e Terapias'),
 ('baricitinib', 'Fármacos e Terapias'),
 ('barriga de cerveja', 'Termos Gerais'),
 ('barriga d’água', 'Doenças'),
 ('bastonet', 'Anatomia'),
 ('bemcentinib', 'Fármacos e Terapias'),
 ('bengala instrumentalizada', 'Equipamentos e Dispositivos'),
 ('beta-amilóide', 'Substâncias Químicas'),
 ('beta-bloqueador', 'Fármacos e Terapias'),
 ('bevacizumab', 'Fármacos e Terapias'),
 ('bio feedback', 'Tecnologia em Saúde'),
 ('bioadesão', 'Biologia Molecular'),
 ('biochip', 'Tecnologia em Saúde'),
 ('bioengenheiro', 'Tecnologia em Saúde'),
 ('bioinformática', 'Tecnologia em Saúde'),
 ('biologia reprodutiva', 'Biologia Molecular'),
 ('biologia sistêmica', 'Biologia Molecular'),
 ('biomarcador', 'Diagnóstico'),
 ('biomembrana', 'Anatomia'),
 ('bioprótese', 'Equipamentos e Dispositivos'),
 ('bipsoro eletrônico', 'Equipamentos e Dispositivos'),
 ('bisturi óptico', 'Equipamentos e Dispositivos'),
 ('biópsia óptica', 'Diagnóstico'),
 ('blockbuster', 'Termos Gerais'),
 ('boceprevir', 'Fármacos e Terapias'),
 ('bombolla', 'Anatomia'),
 ('bombolla ampliada', 'Anatomia'),
 ('bombolla de convivència', 'Epidemiologia e Saúde Pública'),
 ('brensocatib', 'Fármacos e Terapias'),
 ('brequinar', 'Fármacos e Terapias'),
 ('brincidofovir', 'Fármacos e Terapias'),
 ('brometo de piridostigmina', 'Fármacos e Terapias'),
 ('bromhexina', 'Fármacos e Terapias'),
 ('broncoconstrição', 'Fisiologia'),
 ('broncodilatador', 'Fármacos e Terapias'),
 ('broncodilatação', 'Fisiologia'),
 ('bronqui', 'Anatomia'),
 ('bronquiolite', 'Doenças'),
 ('bronquiolitis', 'Doenças'),
 ('bronquitis capil·lar', 'Doenças'),
 ('bronquíol', 'Anatomia'),
 ('brot epidèmic', 'Epidemiologia e Saúde Pública'),
 ('budesonida', 'Fármacos e Terapias'),
 ('bulimia nervosa', 'Psicologia e Psiquiatria'),
 ('cadena de transmissió', 'Epidemiologia e Saúde Pública'),
 ('cadena epidemiològica', 'Epidemiologia e Saúde Pública'),
 ('camostat', 'Fármacos e Terapias'),
 ('camrelizumab', 'Fármacos e Terapias'),
 ('camussa antibaf', 'Equipamentos e Dispositivos'),
 ('canakinumab', 'Fármacos e Terapias'),
 ('capsulotomia anterior estereotáxica por gamma-knife', 'Procedimentos Médicos'),
 ('caramboleira', 'Nutrição e Metabolismo'),
 ('carcinogênese química', 'Doenças'),
 ('careta', 'Equipamentos e Dispositivos'),
 ('cas', 'Epidemiologia e Saúde Pública'),
 ('cas confirmat', 'Epidemiologia e Saúde Pública'),
 ('cas descartat', 'Epidemiologia e Saúde Pública'),
 ('cas possible', 'Epidemiologia e Saúde Pública'),
 ('cas sospitós', 'Epidemiologia e Saúde Pública'),
 ('cas índex', 'Epidemiologia e Saúde Pública'),
 ('casirivimab', 'Fármacos e Terapias'),
 ('casquet', 'Equipamentos e Dispositivos'),
 ('casset', 'Equipamentos e Dispositivos'),
 ('catuama', 'Termos Gerais'),
 ('cavidade pleural', 'Anatomia'),
 ('CD24Fc', 'Fármacos e Terapias'),
 ('cefalea', 'Sintomas e Sinais'),
 ('cefalàlgia', 'Sintomas e Sinais'),
 ('cenicriviroc', 'Fármacos e Terapias'),
 ('ceratoscopia', 'Diagnóstico'),
 ('chip de DNA', 'Tecnologia em Saúde'),
 ('choque hemorrágico', 'Doenças'),
 ('choque séptico', 'Doenças'),
 ('chá de quebra-pedra', 'Nutrição e Metabolismo'),
 ('ciclesonida', 'Fármacos e Terapias'),
 ('cingulotomia anterior', 'Procedimentos Médicos'),
 ('cirurgia a céu aberto', 'Procedimentos Médicos'),
 ('cirurgia fetal a céu aberto', 'Procedimentos Médicos'),
 ('citocina', 'Imunologia'),
 ('civeta', 'Termos Gerais'),
 ('clazakizumab', 'Fármacos e Terapias'),
 ('clofazimina', 'Fármacos e Terapias'),
 ('clonagem reprodutiva', 'Genética e Biologia Molecular'),
 ('clonagem terapêutica', 'Genética e Biologia Molecular'),
 ('cloroquina', 'Fármacos e Terapias'),
 ('clínica', 'Profissionais e Serviços de Saúde'),
 ('coagulação intravascular disseminada', 'Doenças'),
 ('coagulopatia', 'Doenças'),
 ('coagulopatia de consumo', 'Doenças'),
 ('cobertura de vacunació', 'Vacinas e Imunização'),
 ('cobertura vacunal', 'Vacinas e Imunização'),
 ('cobicistat', 'Fármacos e Terapias'),
 ('cogumelo-do-sol', 'Nutrição e Metabolismo'),
 ('colite hemorrágica', 'Doenças'),
 ('colquicina', 'Fármacos e Terapias'),
 ('col·lapse cardiocirculatori', 'Doenças'),
 ('col·lectiu vulnerable de risc', 'Epidemiologia e Saúde Pública'),
 ('Comirnaty', 'Vacinas e Imunização'),
 ('comitè de bioètica', 'Bioética e Leis'),
 ('comorbiditat', 'Doenças'),
 ('complexo de vanádio', 'Substâncias Químicas'),
 ('compte hemàtic', 'Diagnóstico'),
 ('comunicat mèdic d’alta', 'Termos Gerais'),
 ('conestat alfa', 'Fármacos e Terapias'),
 ('confinament', 'Epidemiologia e Saúde Pública'),
 ('confinament perimetral', 'Epidemiologia e Saúde Pública'),
 ('congestió nasal', 'Sintomas e Sinais'),
 ('conjuntivitis', 'Doenças'),
 ('contacte', 'Epidemiologia e Saúde Pública'),
 ('contacte estret', 'Epidemiologia e Saúde Pública'),
 ('contagi', 'Epidemiologia e Saúde Pública'),
 ('contagi directe', 'Epidemiologia e Saúde Pública'),
 ('contagi immediat', 'Epidemiologia e Saúde Pública'),
 ('contagi indirecte', 'Epidemiologia e Saúde Pública'),
 ('contagi mediat', 'Epidemiologia e Saúde Pública'),
 ('contagiositat', 'Epidemiologia e Saúde Pública'),
 ('contenció', 'Epidemiologia e Saúde Pública'),
 ('control', 'Epidemiologia e Saúde Pública'),
 ('convalescència', 'Termos Gerais'),
 ('Convidecia', 'Vacinas e Imunização'),
 ('corba de contagis', 'Epidemiologia e Saúde Pública'),
 ('corba epidèmica', 'Epidemiologia e Saúde Pública'),
 ('CoronaVac', 'Vacinas e Imunização'),
 ('coronavirus', 'Microbiologia e Virologia'),
 ('coronavirus 2 de la síndrome respiratòria', 'Microbiologia e Virologia'),
 ('coronavirus associat a la MERS', 'Microbiologia e Virologia'),
 ('coronavirus associat a la SARS', 'Microbiologia e Virologia'),
 ('coronavirus de la COVID-19', 'Microbiologia e Virologia'),
 ('coronavirus de la MERS', 'Microbiologia e Virologia'),
 ('coronavirus de la SARS', 'Microbiologia e Virologia'),
 ('coréia de sydenham', 'Doenças'),
 ('covid', 'Doenças'),
 ('covid persistent', 'Doenças'),
 ('covid-19', 'Doenças'),
 ('COVID-19', 'Doenças'),
 ('COVID-19 persistent', 'Doenças'),
 ('craniossinostose', 'Doenças'),
 ('cribratge', 'Diagnóstico'),
 ('crise de pânico', 'Psicologia e Psiquiatria'),
 ('crise hipoglicêmica', 'Doenças'),
 ('cristalografia de proteínas', 'Tecnologia em Saúde'),
 ('cromoblastomicose', 'Doenças'),
 ('crotoxina', 'Substâncias Químicas'),
 ('cultiu', 'Microbiologia e Virologia'),
 ('curativo biocompatível', 'Equipamentos e Dispositivos'),
 ('curativo de hidrogel', 'Equipamentos e Dispositivos'),
 ('CVnCoV', 'Vacinas e Imunização'),
 ('cànula nasal', 'Equipamentos e Dispositivos'),
 ('càpsida', 'Anatomia'),
 ('càrrega antigènica', 'Imunologia'),
 ('càrrega viral', 'Microbiologia e Virologia'),
 ('càrrega vírica', 'Microbiologia e Virologia'),
 ('câmara de cintilação híbrida', 'Equipamentos e Dispositivos'),
 ('câncer de boca', 'Doenças'),
 ('câncer de colo de útero', 'Doenças'),
 ('câncer de estômago', 'Doenças'),
 ('câncer de mama', 'Doenças'),
 ('câncer de pele', 'Doenças'),
 ('câncer de próstata', 'Doenças'),
 ('câncer de pulmão', 'Doenças'),
 ('câncer de tireóide', 'Doenças'),
 ('câncer gástrico', 'Doenças'),
 ('cèl·lula B', 'Imunologia'),
 ('cèl·lula T', 'Imunologia'),
 ('célula multipotencial', 'Biologia Molecular'),
 ('córtex cingulado', 'Anatomia'),
 ('danoprevir', 'Fármacos e Terapias'),
 ('darunavir', 'Fármacos e Terapias'),
 ('dazcapistat', 'Fármacos e Terapias'),
 ('defenses', 'Imunologia'),
 ('degeneração macular relacionada à idade', 'Doenças'),
 ('delegat de prevenció', 'Profissionais e Serviços de Saúde'),
 ('depressão alastrante de leão', 'Psicologia e Psiquiatria'),
 ('dermatoscopia', 'Diagnóstico'),
 ('derrame pleural', 'Doenças'),
 ('desconfinament', 'Epidemiologia e Saúde Pública'),
 ('desescalada', 'Epidemiologia e Saúde Pública'),
 ('desescalament', 'Epidemiologia e Saúde Pública'),
 ('deshidrodidemnina B', 'Substâncias Químicas'),
 ('desinfectant', 'Equipamentos e Dispositivos'),
 ('destret respiratori de l’adult', 'Doenças'),
 ('destret respiratori del nadó', 'Doenças'),
 ('detecció precoç', 'Diagnóstico'),
 ('dexametasona', 'Fármacos e Terapias'),
 ('diagnosi', 'Diagnóstico'),
 ('diagnòstic', 'Diagnóstico'),
 ('diarrea', 'Sintomas e Sinais'),
 ('diarréia do viajante', 'Doenças'),
 ('dicroismo circular', 'Tecnologia em Saúde'),
 ('discapacitat', 'Termos Gerais'),
 ('disfonia', 'Sintomas e Sinais'),
 ('disfunção velofaríngea', 'Doenças'),
 ('displàsia alveolar congènita', 'Doenças'),
 ('dispnea', 'Sintomas e Sinais'),
 ('distanciament de seguretat', 'Epidemiologia e Saúde Pública'),
 ('distanciament físic', 'Epidemiologia e Saúde Pública'),
 ('distanàsia', 'Termos Gerais'),
 ('distrofia muscular progressiva', 'Doenças'),
 ('distància de seguretat', 'Epidemiologia e Saúde Pública'),
 ('distància física', 'Epidemiologia e Saúde Pública'),
 ('distúrbio do sono', 'Psicologia e Psiquiatria'),
 ('DNA', 'Genética e Biologia Molecular'),
 ('doença da vaca louca', 'Doenças'),
 ('doença isquêmica do coração', 'Doenças'),
 ('doença reemergente', 'Doenças'),
 ('dol', 'Sintomas e Sinais'),
 ('dolor toràcic', 'Sintomas e Sinais'),
 ('dosi de record', 'Vacinas e Imunização'),
 ('dosi de reforç', 'Vacinas e Imunização'),
 ('droga neuroativa', 'Fármacos e Terapias'),
 ('dímer-D', 'Diagnóstico'),
 ('eculizumab', 'Fármacos e Terapias'),
 ('edatisme', 'Termos Gerais'),
 ('efectivitat vacunal', 'Vacinas e Imunização'),
 ('efeito placebo', 'Psicologia e Psiquiatria'),
 ('eficiència vacunal', 'Vacinas e Imunização'),
 ('eficàcia vacunal', 'Vacinas e Imunização'),
 ('elasomeran', 'Fármacos e Terapias'),
 ('ELISA', 'Diagnóstico'),
 ('elisa in house', 'Diagnóstico'),
 ('elisa indireto', 'Diagnóstico'),
 ('emapalumab', 'Fármacos e Terapias'),
 ('embolcall', 'Equipamentos e Dispositivos'),
 ('embòlia pulmonar', 'Doenças'),
 ('emergència sanitària', 'Termos Gerais'),
 ('emtricitabina', 'Fármacos e Terapias'),
 ('emvododstat', 'Fármacos e Terapias'),
 ('encapsulamento molecular', 'Biologia Molecular'),
 ('encebador', 'Equipamentos e Dispositivos'),
 ('encefalopatia espongiforme', 'Doenças'),
 ('encefalopatia espongiforme bovina', 'Doenças'),
 ('encefalopatia espongiforme felina', 'Doenças'),
 ('endotelina', 'Substâncias Químicas'),
 ('endèmia', 'Epidemiologia e Saúde Pública'),
 ('enoxaparina', 'Fármacos e Terapias'),
 ('enpatoran', 'Fármacos e Terapias'),
 ('ensaio clínico duplo-cego', 'Pesquisa Clínica'),
 ('ensovibep', 'Fármacos e Terapias'),
 ('enxerto orgânico', 'Procedimentos Médicos'),
 ('enxerto periférico heterólogo', 'Procedimentos Médicos'),
 ('enzima cicloxigenase', 'Substâncias Químicas'),
 ('enzima conversora da angiotensina I', 'Substâncias Químicas'),
 ('enzima de reparo', 'Substâncias Químicas'),
 ('enzima degradadora de insulina', 'Substâncias Químicas'),
 ('enzimoimmunoassaig sobre fase sòlida', 'Diagnóstico'),
 ('EPI', 'Equipamentos e Dispositivos'),
 ('epidemiologia', 'Epidemiologia e Saúde Pública'),
 ('epidemiologia matemática', 'Epidemiologia e Saúde Pública'),
 ('epidèmia', 'Epidemiologia e Saúde Pública'),
 ('epilepsia de lobo temporal mesial', 'Doenças'),
 ('epilepsia pós-traumática', 'Doenças'),
 ('equinácea', 'Nutrição e Metabolismo'),
 ('equip de protecció individual', 'Equipamentos e Dispositivos'),
 ('equip de protecció personal', 'Equipamentos e Dispositivos'),
 ('eritropoetina', 'Fármacos e Terapias'),
 ('erradicació', 'Epidemiologia e Saúde Pública'),
 ('ERTO', 'Termos Gerais'),
 ('erva-de-são-joão', 'Nutrição e Metabolismo'),
 ('esclerose lateral amiotrófica', 'Doenças'),
 ('esclerose múltipla', 'Doenças'),
 ('esclerose sistêmica', 'Doenças'),
 ('escovilló', 'Equipamentos e Dispositivos'),
 ('esdeveniment advers', 'Termos Gerais'),
 ('esgotament', 'Psicologia e Psiquiatria'),
 ('esgotament mental', 'Psicologia e Psiquiatria'),
 ('espectrometria de massa', 'Tecnologia em Saúde'),
 ('espectroscopia de fluorescência', 'Tecnologia em Saúde'),
 ('espectroscopia de ressonância nuclear magnética', 'Tecnologia em Saúde'),
 ('esperança de vida', 'Termos Gerais'),
 ('esperança de vida en bona salut', 'Termos Gerais'),
 ('espícula', 'Anatomia'),
 ('esquistossomicida', 'Fármacos e Terapias'),
 ('estacionalitat', 'Epidemiologia e Saúde Pública'),
 ('estadi d’incubació', 'Epidemiologia e Saúde Pública'),
 ('estat d’alarma', 'Termos Gerais'),
 ('estresse oxidativo', 'Doenças'),
 ('estudi clínic', 'Pesquisa Clínica'),
 ('estudi de confirmació terapèutica', 'Pesquisa Clínica'),
 ('estudi de farmacologia humana', 'Pesquisa Clínica'),
 ('estudi de fase 0', 'Pesquisa Clínica'),
 ('estudi de fase I', 'Pesquisa Clínica'),
 ('estudi de fase II', 'Pesquisa Clínica'),
 ('estudi de fase III', 'Pesquisa Clínica'),
 ('estudi de fase IV', 'Pesquisa Clínica'),
 ('estudi de microdosi', 'Pesquisa Clínica'),
 ('estudi d’exploració terapèutica', 'Pesquisa Clínica'),
 ('estudi d’ús terapèutic', 'Pesquisa Clínica'),
 ('estudi preclínic', 'Pesquisa Clínica'),
 ('estímulo aversivo', 'Psicologia e Psiquiatria'),
 ('etesevimab', 'Fármacos e Terapias'),
 ('excés de mortalitat', 'Epidemiologia e Saúde Pública'),
 ('excés de morts', 'Epidemiologia e Saúde Pública'),
 ('expedient de regulació temporal d’ocupació', 'Profissionais e Serviços de Saúde'),
 ('exsudat', 'Diagnóstico'),
 ('exsudat bucofaringi', 'Diagnóstico'),
 ('exsudat nasofaringi', 'Diagnóstico'),
 ('extrato de alho', 'Nutrição e Metabolismo'),
 ('extrato de camapu', 'Nutrição e Metabolismo'),
 ('extrato de pariparoba', 'Nutrição e Metabolismo'),
 ('extubació', 'Procedimentos Médicos'),
 ('factor de risc', 'Epidemiologia e Saúde Pública'),
 ('fagocitosi', 'Imunologia'),
 ('falcoemulsificação', 'Procedimentos Médicos'),
 ('fallada vacunal', 'Vacinas e Imunização'),
 ('fallada vacunal primària', 'Vacinas e Imunização'),
 ('fallada vacunal secundària', 'Vacinas e Imunização'),
 ('fals negatiu', 'Diagnóstico'),
 ('fals positiu', 'Diagnóstico'),
 ('falsa arnica', 'Termos Gerais'),
 ('falsa operação', 'Termos Gerais'),
 ('falta de concentració', 'Psicologia e Psiquiatria'),
 ('fase de contenció', 'Epidemiologia e Saúde Pública'),
 ('fase de mitigació', 'Epidemiologia e Saúde Pública'),
 ('fase IV', 'Pesquisa Clínica'),
 ('fatiga', 'Sintomas e Sinais'),
 ('fatiga mental', 'Sintomas e Sinais'),
 ('fatiga pandèmica', 'Sintomas e Sinais'),
 ('fator de crescimento de fibroblastos', 'Substâncias Químicas'),
 ('fator de estimulação de colônia de granulócito', 'Substâncias Químicas'),
 ('favipiravir', 'Fármacos e Terapias'),
 ('febre', 'Sintomas e Sinais'),
 ('febre do oeste do nilo', 'Doenças'),
 ('febre maculosa', 'Doenças'),
 ('febrícula', 'Sintomas e Sinais'),
 ('fenofibrat', 'Fármacos e Terapias'),
 ('ferritina', 'Diagnóstico'),
 ('fibrilação ventricular', 'Doenças'),
 ('fibrinogen', 'Substâncias Químicas'),
 ('fibrosi', 'Doenças'),
 ('fingolimod', 'Fármacos e Terapias'),
 ('fluid bucofaringi', 'Diagnóstico'),
 ('fluid nasofaringi', 'Diagnóstico'),
 ('fototrombose mediada pela indocianina verde', 'Procedimentos Médicos'),
 ('frotis', 'Diagnóstico'),
 ('fòmit', 'Epidemiologia e Saúde Pública'),
 ('galantamina', 'Fármacos e Terapias'),
 ('galidesivir', 'Fármacos e Terapias'),
 ('Gam-COVID-Vac', 'Vacinas e Imunização'),
 ('gat d’algàlia', 'Termos Gerais'),
 ('GCE', 'Termos Gerais'),
 ('gel antisèptic', 'Equipamentos e Dispositivos'),
 ('gel desinfectant', 'Equipamentos e Dispositivos'),
 ('gel hidroalcohòlic', 'Equipamentos e Dispositivos'),
 ('gel higienitzant', 'Equipamentos e Dispositivos'),
 ('gene dinámico', 'Genética e Biologia Molecular'),
 ('gene expresso', 'Genética e Biologia Molecular'),
 ('genes do imprinting', 'Genética e Biologia Molecular'),
 ('genoma', 'Genética e Biologia Molecular'),
 ('genoma mitocondrial', 'Genética e Biologia Molecular'),
 ('genética molecular', 'Genética e Biologia Molecular'),
 ('gimsilumab', 'Fármacos e Terapias'),
 ('glicosímetro', 'Equipamentos e Dispositivos'),
 ('glucoíris', 'Termos Gerais'),
 ('goflikicept', 'Fármacos e Terapias'),
 ('gomesina', 'Fármacos e Terapias'),
 ('gota de Flügge', 'Epidemiologia e Saúde Pública'),
 ('goteta', 'Epidemiologia e Saúde Pública'),
 ('goteta respiratòria', 'Epidemiologia e Saúde Pública'),
 ('gotícula respiratòria', 'Epidemiologia e Saúde Pública'),
 ('greu', 'Termos Gerais'),
 ('grup bombolla', 'Epidemiologia e Saúde Pública'),
 ('grup de convivència', 'Epidemiologia e Saúde Pública'),
 ('grup de convivència ampliada', 'Epidemiologia e Saúde Pública'),
 ('grup de convivència estable', 'Epidemiologia e Saúde Pública'),
 ('grup de risc', 'Epidemiologia e Saúde Pública'),
 ('guant', 'Equipamentos e Dispositivos'),
 ('hantavirose', 'Doenças'),
 ('hemoderivado', 'Termos Gerais'),
 ('hemograma', 'Diagnóstico'),
 ('hemopressina', 'Substâncias Químicas'),
 ('hemopure', 'Substâncias Químicas'),
 ('heparina', 'Fármacos e Terapias'),
 ('hepatotoxicitat', 'Doenças'),
 ('hidrocarboneto policíclico aromático', 'Substâncias Químicas'),
 ('hidroxiapatita', 'Substâncias Químicas'),
 ('hidroxicloroquina', 'Fármacos e Terapias'),
 ('higiene', 'Epidemiologia e Saúde Pública'),
 ('higiene de mans', 'Epidemiologia e Saúde Pública'),
 ('hiperbilirrubinemia', 'Doenças'),
 ('hipernasalidade', 'Sintomas e Sinais'),
 ('hiperplasia epitelial', 'Doenças'),
 ('hipoestèsia gustativa', 'Sintomas e Sinais'),
 ('hipoestèsia olfactòria', 'Sintomas e Sinais'),
 ('hipogèusia', 'Sintomas e Sinais'),
 ('hipoxèmia', 'Doenças'),
 ('hipoòsmia', 'Sintomas e Sinais'),
 ('hipòsmia', 'Sintomas e Sinais'),
 ('hipòxia', 'Doenças'),
 ('història clínica', 'Termos Gerais'),
 ('homocisteína', 'Substâncias Químicas'),
 ('homocistinúria', 'Doenças'),
 ('hormônio de crescimento', 'Fármacos e Terapias'),
 ('hormônio de crescimento biossintético', 'Fármacos e Terapias'),
 ('hormônio regulador', 'Substâncias Químicas'),
 ('hostatger', 'Microbiologia e Virologia'),
 ('hoste', 'Microbiologia e Virologia'),
 ('hoste intermediari', 'Microbiologia e Virologia'),
 ('IA', 'Tecnologia em Saúde'),
 ('ibuprofèn', 'Fármacos e Terapias'),
 ('icatibant', 'Fármacos e Terapias'),
 ('icterícia fisiológica', 'Doenças'),
 ('IECA', 'Fármacos e Terapias'),
 ('ilhota pancreática', 'Anatomia'),
 ('imdevimab', 'Fármacos e Terapias'),
 ('immune', 'Imunologia'),
 ('immunitari -ària', 'Imunologia'),
 ('immunitat', 'Imunologia'),
 ('immunitat activa', 'Imunologia'),
 ('immunitat adaptativa', 'Imunologia'),
 ('immunitat adquirida', 'Imunologia'),
 ('immunitat col·lectiva', 'Imunologia'),
 ('immunitat congènita', 'Imunologia'),
 ('immunitat de comunitat', 'Imunologia'),
 ('immunitat de grup', 'Imunologia'),
 ('immunitat específica ', 'Imunologia'),
 ('immunitat específica artificial', 'Imunologia'),
 ('immunitat específica espontània', 'Imunologia'),
 ('immunitat específica intencionada', 'Imunologia'),
 ('immunitat específica natural', 'Imunologia'),
 ('immunitat específica no intencionada', 'Imunologia'),
 ('immunitat específica passiva', 'Imunologia'),
 ('immunitat inespecífica', 'Imunologia'),
 ('immunitat innata', 'Imunologia'),
 ('immunitat natural', 'Imunologia'),
 ('immunització', 'Vacinas e Imunização'),
 ('immunització activa', 'Vacinas e Imunização'),
 ('immunocromatografia', 'Diagnóstico'),
 ('immunogen -ògena', 'Imunologia'),
 ('immunogenicitat', 'Imunologia'),
 ('immunoglobulina', 'Imunologia'),
 ('immunoglobulina G', 'Imunologia'),
 ('immunoglobulina M', 'Imunologia'),
 ('immunològic -a', 'Imunologia'),
 ('imunossensor amperométrico', 'Equipamentos e Dispositivos'),
 ('incapacitat', 'Termos Gerais'),
 ('incapacitat permanent', 'Termos Gerais'),
 ('incapacitat temporal', 'Termos Gerais'),
 ('incidència', 'Epidemiologia e Saúde Pública'),
 ('incidència acumulada', 'Epidemiologia e Saúde Pública'),
 ('incubació', 'Epidemiologia e Saúde Pública'),
 ('infarto medular', 'Doenças'),
 ('infecció', 'Doenças'),
 ('infecció hospitalària', 'Doenças'),
 ('infecció nosocomial', 'Doenças'),
 ('infecció per gotetes', 'Doenças'),
 ('infectologia', 'Doenças'),
 ('infecção perinatal', 'Doenças'),
 ('infiltrat', 'Doenças'),
 ('inflamació', 'Doenças'),
 ('infodèmia', 'Epidemiologia e Saúde Pública'),
 ('inhibidor de l’enzim conversiu', 'Fármacos e Terapias'),
 ('insomni', 'Psicologia e Psiquiatria'),
 ('insuficiência cardíaca crônica', 'Doenças'),
 ('insuficiência cardíaca grave', 'Doenças'),
 ('insuficiência renal aguda', 'Doenças'),
 ('insulina encapsulada', 'Fármacos e Terapias'),
 ('insulina transgênica', 'Fármacos e Terapias'),
 ('intel·ligència artificial', 'Tecnologia em Saúde'),
 ('interferon gama', 'Fármacos e Terapias'),
 ('interferó', 'Fármacos e Terapias'),
 ('interferó beta', 'Fármacos e Terapias'),
 ('intubació', 'Procedimentos Médicos'),
 ('IP', 'Termos Gerais'),
 ('isoflavona aglicona', 'Substâncias Químicas'),
 ('isquemia cerebral', 'Doenças'),
 ('IT', 'Termos Gerais'),
 ('jacalina', 'Substâncias Químicas'),
 ('jogador patológico', 'Psicologia e Psiquiatria'),
 ('justícia distributiva', 'Bioética e Leis'),
 ('kava-kava', 'Nutrição e Metabolismo'),
 ('lactat-deshidrogenasa', 'Diagnóstico'),
 ('lanadelumab', 'Fármacos e Terapias'),
 ('latència', 'Epidemiologia e Saúde Pública'),
 ('LDH', 'Diagnóstico'),
 ('leishmaniose cutâneo-mucosa', 'Doenças'),
 ('leishmaniose tegumentar americana', 'Doenças'),
 ('lenzilumab', 'Fármacos e Terapias'),
 ('leptina', 'Substâncias Químicas'),
 ('leronlimab', 'Fármacos e Terapias'),
 ('lesão medular', 'Doenças'),
 ('LET', 'Termos Gerais'),
 ('leucemia mielóide aguda', 'Doenças'),
 ('leucemia mielóide crônica', 'Doenças'),
 ('limfocitopènia', 'Doenças'),
 ('limfopènia', 'Doenças'),
 ('limfòcit', 'Imunologia'),
 ('limfòcit B', 'Imunologia'),
 ('limfòcit de memòria', 'Imunologia'),
 ('limfòcit T', 'Imunologia'),
 ('limitació de l’esforç terapèutic', 'Profissionais e Serviços de Saúde'),
 ('linfoma de burkitt', 'Doenças'),
 ('lopap', 'Fármacos e Terapias'),
 ('lopinavir', 'Fármacos e Terapias'),
 ('líquido cefalorraquidiano', 'Diagnóstico'),
 ('líquor', 'Diagnóstico'),
 ('lúpus eritematoso sistêmico', 'Doenças'),
 ('macròfag', 'Imunologia'),
 ('mal da vaca louca', 'Doenças'),
 ('mal de alzheimer', 'Doenças'),
 ('mal de cap', 'Sintomas e Sinais'),
 ('mal de chagas', 'Doenças'),
 ('mal de costat', 'Termos Gerais'),
 ('mal de creutzfeldt-jacob', 'Doenças'),
 ('mal de lutz', 'Doenças'),
 ('mal de pit', 'Termos Gerais'),
 ('malaltia del coronavirus 2019', 'Doenças'),
 ('mamica de cadela', 'Termos Gerais'),
 ('marcador inflamatori', 'Diagnóstico'),
 ('mareig', 'Sintomas e Sinais'),
 ('mascareta', 'Equipamentos e Dispositivos'),
 ('mascareta higiènica', 'Equipamentos e Dispositivos'),
 ('mascareta quirúrgica', 'Equipamentos e Dispositivos'),
 ('MEDI 3506', 'Fármacos e Terapias'),
 ('medicalitzar', 'Profissionais e Serviços de Saúde'),
 ('medicina avaluadora', 'Profissionais e Serviços de Saúde'),
 ('medicina comportamental', 'Profissionais e Serviços de Saúde'),
 ('medicina à distância', 'Profissionais e Serviços de Saúde'),
 ('memantina', 'Fármacos e Terapias'),
 ('memòria immunitària', 'Imunologia'),
 ('meplazumab', 'Fármacos e Terapias'),
 ('MERS', 'Doenças'),
 ('MERS-CoV', 'Microbiologia e Virologia'),
 ('mesura de contenció', 'Epidemiologia e Saúde Pública'),
 ('metaplasia intestinal', 'Doenças'),
 ('metapneumovírus', 'Microbiologia e Virologia'),
 ('metilprednisolona', 'Fármacos e Terapias'),
 ('miastenia grave', 'Doenças'),
 ('microagulha', 'Equipamentos e Dispositivos'),
 ('microarray', 'Tecnologia em Saúde'),
 ('microesferas biodegradáveis', 'Equipamentos e Dispositivos'),
 ('microflora intestinal', 'Microbiologia e Virologia'),
 ('microscopia eletrônica de varredura', 'Tecnologia em Saúde'),
 ('microtrans', 'Tecnologia em Saúde'),
 ('mielomeningocele', 'Doenças'),
 ('mimivírus', 'Microbiologia e Virologia'),
 ('miàlgia', 'Sintomas e Sinais'),
 ('molnupiravir', 'Fármacos e Terapias'),
 ('monitoratge', 'Diagnóstico'),
 ('montelukast', 'Fármacos e Terapias'),
 ('mort digna', 'Bioética e Leis'),
 ('mortalitat', 'Epidemiologia e Saúde Pública'),
 ('mostra bucofaríngia', 'Diagnóstico'),
 ('mostra nasofaríngia', 'Diagnóstico'),
 ('mostra orofaríngia', 'Diagnóstico'),
 ('mostra rinofaríngia', 'Diagnóstico'),
 ('mRNA', 'Genética e Biologia Molecular'),
 ('mucosite oral', 'Doenças'),
 ('muleta instrumentalizada', 'Equipamentos e Dispositivos'),
 ('mupadolimab', 'Fármacos e Terapias'),
 ('muriac', 'Fármacos e Terapias'),
 ('muricec', 'Fármacos e Terapias'),
 ('mutació', 'Genética e Biologia Molecular'),
 ('màscara', 'Equipamentos e Dispositivos'),
 ('màscara amb filtre de partícules', 'Equipamentos e Dispositivos'),
 ('màscara autofiltrant', 'Equipamentos e Dispositivos'),
 ('màscara FFP', 'Equipamentos e Dispositivos'),
 ('màscara higiènica', 'Equipamentos e Dispositivos'),
 ('màscara mèdica', 'Equipamentos e Dispositivos'),
 ('màscara quirúrgica', 'Equipamentos e Dispositivos'),
 ('mão de são carlos', 'Termos Gerais'),
 ('nafamostat', 'Fármacos e Terapias'),
 ('nebulització', 'Procedimentos Médicos'),
 ('nebulitzador', 'Equipamentos e Dispositivos'),
 ('neuromorfometria', 'Tecnologia em Saúde'),
 ('neurônio biônico', 'Tecnologia em Saúde'),
 ('nitrato de prata', 'Substâncias Químicas'),
 ('no inici de tractament', 'Termos Gerais'),
 ('nombre reproductiu bàsic', 'Epidemiologia e Saúde Pública'),
 ('nova normalitat', 'Termos Gerais'),
 ('NVX-CoV2373', 'Vacinas e Imunização'),
 ('nàusea', 'Sintomas e Sinais'),
 ('núcleo mediano da rafe', 'Anatomia'),
 ('núcleo paraventricular', 'Anatomia'),
 ('obstinació terapèutica', 'Profissionais e Serviços de Saúde'),
 ('odontogeriatria', 'Termos Gerais'),
 ('ofec', 'Termos Gerais'),
 ('OMS', 'Profissionais e Serviços de Saúde'),
 ('onada', 'Epidemiologia e Saúde Pública'),
 ('onada epidèmica', 'Epidemiologia e Saúde Pública'),
 ('OP-101', 'Fármacos e Terapias'),
 ('opaganib', 'Fármacos e Terapias'),
 ('Organització Mundial de la Salut', 'Profissionais e Serviços de Saúde'),
 ('oseltamivir', 'Fármacos e Terapias'),
 ('osseointegração', 'Termos Gerais'),
 ('otilimab', 'Fármacos e Terapias'),
 ('oxigenació', 'Fisiologia'),
 ('oxigenoteràpia', 'Procedimentos Médicos'),
 ('pacient zero', 'Epidemiologia e Saúde Pública'),
 ('pandèmia', 'Epidemiologia e Saúde Pública'),
 ('pangolí', 'Termos Gerais'),
 ('pantalla facial', 'Equipamentos e Dispositivos'),
 ('papiloma vírus', 'Microbiologia e Virologia'),
 ('paràsit', 'Microbiologia e Virologia'),
 ('passaport d’immunitat', 'Vacinas e Imunização'),
 ('passaport immunitari', 'Vacinas e Imunização'),
 ('passaport immunològic', 'Vacinas e Imunização'),
 ('pata-de-vaca', 'Termos Gerais'),
 ('patogen -ògena', 'Microbiologia e Virologia'),
 ('patogenicitat', 'Microbiologia e Virologia'),
 ('pauta de vacunació', 'Vacinas e Imunização'),
 ('pauta vacunal', 'Vacinas e Imunização'),
 ('PCR', 'Diagnóstico'),
 ('pele artificial', 'Equipamentos e Dispositivos'),
 ('pemziviptadil', 'Fármacos e Terapias'),
 ('penelló', 'Termos Gerais'),
 ('peplòmer', 'Anatomia'),
 ('peritatge mèdic', 'Profissionais e Serviços de Saúde'),
 ('perlecan', 'Substâncias Químicas'),
 ('perniosi', 'Doenças'),
 ('pernió', 'Doenças'),
 ('persona de risc per a la COVID-19', 'Epidemiologia e Saúde Pública'),
 ('persona especialment sensible a la COVID-19', 'Epidemiologia e Saúde Pública'),
 ('persona vulnerable a la COVID-19', 'Epidemiologia e Saúde Pública'),
 ('període de latència', 'Epidemiologia e Saúde Pública'),
 ('període de reacció', 'Epidemiologia e Saúde Pública'),
 ('període d’incubació', 'Epidemiologia e Saúde Pública'),
 ('període d’infecció', 'Epidemiologia e Saúde Pública'),
 ('període latent', 'Epidemiologia e Saúde Pública'),
 ('pic de contagis', 'Epidemiologia e Saúde Pública'),
 ('pic epidèmic', 'Epidemiologia e Saúde Pública'),
 ('picnocàrdia', 'Doenças'),
 ('pinça óptica', 'Equipamentos e Dispositivos'),
 ('piolho de cama', 'Microbiologia e Virologia'),
 ('pla de contingència contra la COVID-19', 'Epidemiologia e Saúde Pública'),
 ('placebo', 'Psicologia e Psiquiatria'),
 ('pleurodese', 'Procedimentos Médicos'),
 ('plitidepsina', 'Fármacos e Terapias'),
 ('pluma grande', 'Termos Gerais'),
 ('pneumonia asiática', 'Doenças'),
 ('pneumònia', 'Doenças'),
 ('pneumònia d’aspiració congènita', 'Doenças'),
 ('població diana', 'Epidemiologia e Saúde Pública'),
 ('població objectiu', 'Epidemiologia e Saúde Pública'),
 ('població sentinella', 'Epidemiologia e Saúde Pública'),
 ('polaina', 'Termos Gerais'),
 ('policàrdia', 'Doenças'),
 ('poliparasitismo', 'Doenças'),
 ('porfíria aguda intermitente', 'Doenças'),
 ('potencial evocado', 'Diagnóstico'),
 ('prednisolona', 'Fármacos e Terapias'),
 ('prevalença', 'Epidemiologia e Saúde Pública'),
 ('primovacunació', 'Vacinas e Imunização'),
 ('principi de beneficència', 'Bioética e Leis'),
 ('principi de no-maleficència', 'Bioética e Leis'),
 ('principi de precaució', 'Bioética e Leis'),
 ('priorització', 'Profissionais e Serviços de Saúde'),
 ('profilàctica', 'Vacinas e Imunização'),
 ('proteïna C reactiva', 'Diagnóstico'),
 ('proteïna de l’espícula', 'Anatomia'),
 ('proteïna espícula', 'Anatomia'),
 ('proteïna estructural', 'Anatomia'),
 ('proteïna S', 'Anatomia'),
 ('prova antigènica', 'Diagnóstico'),
 ('prova de mostres agrupades', 'Diagnóstico'),
 ('prova de mostres combinades', 'Diagnóstico'),
 ('prova diagnòstica amb ELISA', 'Diagnóstico'),
 ('prova diagnòstica amb PCR', 'Diagnóstico'),
 ('prova diagnòstica ràpida', 'Diagnóstico'),
 ('prova d’antígens', 'Diagnóstico'),
 ('prova immunològica', 'Diagnóstico'),
 ('prova PCR', 'Diagnóstico'),
 ('prova ràpida', 'Diagnóstico'),
 ('prova serològica', 'Diagnóstico'),
 ('pròdrom', 'Sintomas e Sinais'),
 ('pró-insulina', 'Substâncias Químicas'),
 ('pròtese de Takimoto', 'Equipamentos e Dispositivos'),
 ('ptose palpebral', 'Doenças'),
 ('pulmonia', 'Doenças'),
 ('pulmó de xoc', 'Doenças'),
 ('punt d’injecció', 'Termos Gerais'),
 ('punt d’inoculació', 'Termos Gerais'),
 ('qualitat de vida', 'Termos Gerais'),
 ('quarantena', 'Epidemiologia e Saúde Pública'),
 ('quarantenar', 'Epidemiologia e Saúde Pública'),
 ('quarantenat -ada', 'Epidemiologia e Saúde Pública'),
 ('QV', 'Termos Gerais'),
 ('RAC', 'Termos Gerais'),
 ('radiocirurgia', 'Procedimentos Médicos'),
 ('radiografia', 'Diagnóstico'),
 ('radiòmica', 'Tecnologia em Saúde'),
 ('raman', 'Tecnologia em Saúde'),
 ('rapamicina', 'Fármacos e Terapias'),
 ('raspallet', 'Termos Gerais'),
 ('rastreig de contactes', 'Epidemiologia e Saúde Pública'),
 ('rastrejador de contactes | rastrejadora de', 'Profissionais e Serviços de Saúde'),
 ('ratapenada', 'Termos Gerais'),
 ('ratapinyada', 'Termos Gerais'),
 ('rato de rabo peludo', 'Termos Gerais'),
 ('ratpenat', 'Termos Gerais'),
 ('ratpenat de ferradura petit', 'Termos Gerais'),
 ('RAV', 'Termos Gerais'),
 ('ravulizumab', 'Fármacos e Terapias'),
 ('razão de chances', 'Epidemiologia e Saúde Pública'),
 ('reabsorció dentária', 'Termos Gerais'),
 ('reacció adversa a vacuna', 'Vacinas e Imunização'),
 ('reacció en cadena per la polimerasa', 'Diagnóstico'),
 ('reacció general', 'Vacinas e Imunização'),
 ('reacció local', 'Vacinas e Imunização'),
 ('reacció sistèmica', 'Vacinas e Imunização'),
 ('rebrot epidèmic', 'Epidemiologia e Saúde Pública'),
 ('rebrotada epidèmica', 'Epidemiologia e Saúde Pública'),
 ('recaiguda', 'Doenças'),
 ('recepció, acollida i classificació', 'Profissionais e Serviços de Saúde'),
 ('recerca de contactes', 'Epidemiologia e Saúde Pública'),
 ('recidiva', 'Doenças'),
 ('recrudescència', 'Doenças'),
 ('rede neural artificial', 'Tecnologia em Saúde'),
 ('regdanvimab', 'Fármacos e Terapias'),
 ('rehabilitació respiratòria', 'Reabilitação'),
 ('reinfecció', 'Doenças'),
 ('remdesivir', 'Fármacos e Terapias'),
 ('rentada de mans', 'Epidemiologia e Saúde Pública'),
 ('rentat de mans', 'Epidemiologia e Saúde Pública'),
 ('reservori', 'Microbiologia e Virologia'),
 ('respiració artificial', 'Procedimentos Médicos'),
 ('respirador', 'Equipamentos e Dispositivos'),
 ('resposta immunitària', 'Imunologia'),
 ('ressonància magnètica funcional', 'Diagnóstico'),
 ('retinol binding protein', 'Substâncias Químicas'),
 ('retrovirus', 'Microbiologia e Virologia'),
 ('revaccinació', 'Vacinas e Imunização'),
 ('revacunació', 'Vacinas e Imunização'),
 ('ribavirina', 'Fármacos e Terapias'),
 ('ritonavir', 'Fármacos e Terapias'),
 ('RNA', 'Genética e Biologia Molecular'),
 ('RNA missatger', 'Genética e Biologia Molecular'),
 ('ruxolitinib', 'Fármacos e Terapias'),
 ('sagüi de tufo branco', 'Termos Gerais'),
 ('sal de escopolamina', 'Substâncias Químicas'),
 ('salgadão', 'Termos Gerais'),
 ('salt d’espècie', 'Microbiologia e Virologia'),
 ('salut en el treball', 'Epidemiologia e Saúde Pública'),
 ('salut laboral', 'Epidemiologia e Saúde Pública'),
 ('salut pública', 'Epidemiologia e Saúde Pública'),
 ('samambaia das taperas', 'Termos Gerais'),
 ('sanitarització', 'Epidemiologia e Saúde Pública'),
 ('sarcoma de ewing', 'Doenças'),
 ('sarilumab', 'Fármacos e Terapias'),
 ('SARS', 'Doenças'),
 ('SARS-CoV', 'Microbiologia e Virologia'),
 ('SARS-CoV-2', 'Microbiologia e Virologia'),
 ('SDRA', 'Doenças'),
 ('secreció de prolactina', 'Substâncias Químicas'),
 ('sedació', 'Fármacos e Terapias'),
 ('selinexor', 'Fármacos e Terapias'),
 ('semiologia', 'Diagnóstico'),
 ('seqüela', 'Doenças'),
 ('serologia', 'Diagnóstico'),
 ('seroprevalença', 'Epidemiologia e Saúde Pública'),
 ('seroteràpia', 'Fármacos e Terapias'),
 ('serotip', 'Microbiologia e Virologia'),
 ('serotipus', 'Microbiologia e Virologia'),
 ('serovar', 'Microbiologia e Virologia'),
 ('servei de prevenció', 'Profissionais e Serviços de Saúde'),
 ('servei d’atenció de salut a domicili', 'Profissionais e Serviços de Saúde'),
 ('shitake', 'Nutrição e Metabolismo'),
 ('signe', 'Sintomas e Sinais'),
 ('siltuximab', 'Fármacos e Terapias'),
 ('simocaína', 'Fármacos e Terapias'),
 ('simptomatologia', 'Sintomas e Sinais'),
 ('sincropèxia', 'Doenças'),
 ('sindèmia', 'Epidemiologia e Saúde Pública'),
 ('siròlimus', 'Fármacos e Terapias'),
 ('sistema de temporización', 'Tecnologia em Saúde'),
 ('sistema endócrino', 'Anatomia'),
 ('sistema límbico', 'Anatomia'),
 ('sistema nervoso parassimpático', 'Anatomia'),
 ('sistema nervoso periférico', 'Anatomia'),
 ('soca', 'Termos Gerais'),
 ('socialització', 'Epidemiologia e Saúde Pública'),
 ('sonda', 'Equipamentos e Dispositivos'),
 ('sonda molecular', 'Equipamentos e Dispositivos'),
 ('soro hiperimune', 'Fármacos e Terapias'),
 ('sotrovimab', 'Fármacos e Terapias'),
 ('Spikevax', 'Vacinas e Imunização'),
 ('Sputnik V', 'Vacinas e Imunização'),
 ('SRAG', 'Doenças'),
 ('subasumstat', 'Fármacos e Terapias'),
 ('supercontagiador -a', 'Epidemiologia e Saúde Pública'),
 ('superpropagador -a', 'Epidemiologia e Saúde Pública'),
 ('suport vital', 'Procedimentos Médicos'),
 ('susceptible', 'Imunologia'),
 ('sèpsia', 'Doenças'),
 ('símptoma', 'Sintomas e Sinais'),
 ('síndrome da fadiga crônica', 'Doenças'),
 ('síndrome da rubéola congênita', 'Doenças'),
 ('síndrome de turner', 'Doenças'),
 ('síndrome del destret respiratori agut', 'Doenças'),
 ('síndrome del destret respiratori de l’adult', 'Doenças'),
 ('síndrome del destret respiratori del nadó', 'Doenças'),
 ('síndrome do desconforto respiratório', 'Doenças'),
 ('síndrome hemolítica urêmica', 'Doenças'),
 ('síndrome post COVID-19', 'Doenças'),
 ('síndrome respiratòria aguda greu', 'Doenças'),
 ('síndrome respiratòria de l’Orient Mitjà', 'Doenças'),
 ('síndrome respiratória aguda severa', 'Doenças'),
 ('talidomida', 'Fármacos e Terapias'),
 ('tapament', 'Termos Gerais'),
 ('taquicàrdia', 'Doenças'),
 ('taquisistòlia', 'Doenças'),
 ('taxa bruta de mortalitat', 'Epidemiologia e Saúde Pública'),
 ('taxa de contagi', 'Epidemiologia e Saúde Pública'),
 ('taxa de letalitat', 'Epidemiologia e Saúde Pública'),
 ('taxa de mortalitat', 'Epidemiologia e Saúde Pública'),
 ('teleconsulta', 'Profissionais e Serviços de Saúde'),
 ('telemedicina', 'Profissionais e Serviços de Saúde'),
 ('teletreball', 'Termos Gerais'),
 ('tempesta de citocines', 'Doenças'),
 ('temps de convalescència', 'Termos Gerais'),
 ('temps de protrombina', 'Diagnóstico'),
 ('temps de Quick', 'Diagnóstico'),
 ('temps de recuperació', 'Termos Gerais'),
 ('tenofovir', 'Fármacos e Terapias'),
 ('terapia de reposição hormonal', 'Fármacos e Terapias'),
 ('terapia fotodinâmica', 'Procedimentos Médicos'),
 ('terapia gênica', 'Fármacos e Terapias'),
 ('terminal nervoso simpático', 'Anatomia'),
 ('test d’anticossos', 'Diagnóstico'),
 ('test d’antígens', 'Diagnóstico'),
 ('test immunològic', 'Diagnóstico'),
 ('test PCR', 'Diagnóstico'),
 ('test per agrupament de mostres', 'Diagnóstico'),
 ('test per combinació de mostres', 'Diagnóstico'),
 ('test ràpid', 'Diagnóstico'),
 ('test serològic', 'Diagnóstico'),
 ('testatge massiu', 'Diagnóstico'),
 ('teste de carga viral', 'Diagnóstico'),
 ('teste de exercício cardiorrespiratório', 'Diagnóstico'),
 ('tixagevimab', 'Fármacos e Terapias'),
 ('toc de queda', 'Psicologia e Psiquiatria'),
 ('tocilizumab', 'Fármacos e Terapias'),
 ('topógrafo intracirúrgico', 'Equipamentos e Dispositivos'),
 ('tos', 'Sintomas e Sinais'),
 ('tos productiva', 'Sintomas e Sinais'),
 ('tos seca', 'Sintomas e Sinais'),
 ('tovalloleta antibaf', 'Equipamentos e Dispositivos'),
 ('tozinameran', 'Vacinas e Imunização'),
 ('tractament amb oxigen', 'Procedimentos Médicos'),
 ('tractament ambulatori', 'Procedimentos Médicos'),
 ('transcriptoma', 'Genética e Biologia Molecular'),
 ('transmissible', 'Microbiologia e Virologia'),
 ('transmissió', 'Microbiologia e Virologia'),
 ('transmissió comunitària', 'Microbiologia e Virologia'),
 ('transmissió horitzontal', 'Microbiologia e Virologia'),
 ('transmissió vertical', 'Microbiologia e Virologia'),
 ('transtirretina', 'Termos Gerais'),
 ('transtorno cognitivo', 'Psicologia e Psiquiatria'),
 ('transtorno do pânico', 'Psicologia e Psiquiatria'),
 ('transtorno obsessivo compulsivo', 'Psicologia e Psiquiatria'),
 ('traqueotomia', 'Procedimentos Médicos'),
 ('traçabilitat', 'Termos Gerais'),
 ('treball a distància', 'Termos Gerais'),
 ('triatge', 'Profissionais e Serviços de Saúde'),
 ('tripanossomicida', 'Fármacos e Terapias'),
 ('tripanossomíase americana', 'Doenças'),
 ('trocáter', 'Equipamentos e Dispositivos'),
 ('trombe', 'Termos Gerais'),
 ('trombosi', 'Doenças'),
 ('trombus', 'Doenças'),
 ('TRV027', 'Fármacos e Terapias'),
 ('tula de besouro', 'Termos Gerais'),
 ('tumor de erlich', 'Doenças'),
 ('tumor de walker', 'Doenças'),
 ('tunicato', 'Termos Gerais'),
 ('técnica de sorting', 'Tecnologia em Saúde'),
 ('técnica sage', 'Tecnologia em Saúde'),
 ('títol d’anticossos', 'Diagnóstico'),
 ('ubiquitina', 'Substâncias Químicas'),
 ('UCI', 'Procedimentos Médicos'),
 ('ulleres nasals', 'Equipamentos e Dispositivos'),
 ('umifenovir', 'Fármacos e Terapias'),
 ('unitat de cures intensives', 'Procedimentos Médicos'),
 ('unitat de vigilància intensiva', 'Procedimentos Médicos'),
 ('urticària', 'Doenças'),
 ('UVI', 'Procedimentos Médicos'),
 ('vaccinació', 'Vacinas e Imunização'),
 ('vaccí', 'Vacinas e Imunização'),
 ('vacina autóloga', 'Vacinas e Imunização'),
 ('vacina de DNA', 'Vacinas e Imunização'),
 ('vacina quádrupla', 'Vacinas e Imunização'),
 ('vacina', 'Vacinas e Imunização'),
 ('vacina anti COVID-19', 'Vacinas e Imunização'),
 ('vacina antivírica', 'Vacinas e Imunização'),
 ('vacina AstraZeneca', 'Vacinas e Imunização'),
 ('vacina BBIBP-CorV', 'Vacinas e Imunização'),
 ('vacina CanSino', 'Vacinas e Imunização'),
 ('vacina contra la COVID-19', 'Vacinas e Imunização'),
 ('vacina CureVac', 'Vacinas e Imunização'),
 ('vacina de Wuhan', 'Vacinas e Imunização'),
 ('vacina d’ARN missatger', 'Vacinas e Imunização'),
 ('vacina d’ARNm', 'Vacinas e Imunização'),
 ('vacina d’mRNA', 'Vacinas e Imunização'),
 ('vacina d’RNA missatger', 'Vacinas e Imunização'),
 ('vacina Gamaleya', 'Vacinas e Imunização'),
 ('vacina Janssen', 'Vacinas e Imunização'),
 ('vacina Johnson &amp; Johnson', 'Vacinas e Imunização'),
 ('vacina Moderna', 'Vacinas e Imunização'),
 ('vacina NovaVax', 'Vacinas e Imunização'),
 ('vacina Oxford-AstraZeneca', 'Vacinas e Imunização'),
 ('vacina Pfizer/BioNTech', 'Vacinas e Imunização'),
 ('vacina preventiva', 'Vacinas e Imunização'),
 ('vacina profilàctica', 'Vacinas e Imunização'),
 ('vacina Sinovac', 'Vacinas e Imunização'),
 ('vacina VeroCell', 'Vacinas e Imunização'),
 ('vacina vírica', 'Vacinas e Imunização'),
 ('vacunació', 'Vacinas e Imunização'),
 ('vacunació primària', 'Vacinas e Imunização'),
 ('vafidemstat', 'Fármacos e Terapias'),
 ('variant', 'Microbiologia e Virologia'),
 ('variant de preocupació', 'Microbiologia e Virologia'),
 ('variant d’interès', 'Microbiologia e Virologia'),
 ('variant preocupant', 'Microbiologia e Virologia'),
 ('variant vírica', 'Microbiologia e Virologia'),
 ('varicela-zoster', 'Microbiologia e Virologia'),
 ('Vaxzevria', 'Vacinas e Imunização'),
 ('veia porta', 'Anatomia'),
 ('velocitat reproductiva bàsica', 'Epidemiologia e Saúde Pública'),
 ('velocitat reproductiva efectiva', 'Epidemiologia e Saúde Pública'),
 ('velocitat reproductiva empírica', 'Epidemiologia e Saúde Pública'),
 ('ventilació', 'Procedimentos Médicos'),
 ('ventilació mecànica', 'Procedimentos Médicos'),
 ('via d’administració', 'Fármacos e Terapias'),
 ('videodermatoscópio', 'Equipamentos e Dispositivos'),
 ('videomicroscopia', 'Tecnologia em Saúde'),
 ('vidofludimús', 'Fármacos e Terapias'),
 ('viricida', 'Substâncias Químicas'),
 ('virió', 'Microbiologia e Virologia'),
 ('virulència', 'Microbiologia e Virologia'),
 ('virus', 'Microbiologia e Virologia'),
 ('virus de la COVID-19', 'Microbiologia e Virologia'),
 ('visera de protecció', 'Equipamentos e Dispositivos'),
 ('VOC', 'Microbiologia e Virologia'),
 ('VOI', 'Microbiologia e Virologia'),
 ('voliac', 'Fármacos e Terapias'),
 ('vorapaxar', 'Fármacos e Terapias'),
 ('vírus amarílico', 'Microbiologia e Virologia'),
 ('vírus cantagalo', 'Microbiologia e Virologia'),
 ('vírus respiratório sincicial', 'Microbiologia e Virologia'),
 ('vòmit', 'Sintomas e Sinais'),
 ('xenotransplante', 'Procedimentos Médicos'),
 ('xoc', 'Doenças'),
 ('zilucoplan', 'Fármacos e Terapias'),
 ('zoonosi', 'Doenças'),
 ('zoonòtic -a', 'Microbiologia e Virologia'),
 ('zorecimeran', 'Fármacos e Terapias'),
 ('àcid desoxiribonucleic', 'Genética e Biologia Molecular'),
 ('àcid ribonucleic', 'Genética e Biologia Molecular'),
 ('ácido acetilsalicílico', 'Substâncias Químicas'),
 ('ácido caínico', 'Substâncias Químicas'),
 ('ácido gama-aminobutírico', 'Substâncias Químicas'),
 ('èczema', 'Doenças'),
 ('èmesi', 'Sintomas e Sinais'),
 ('éfedra', 'Termos Gerais'),
 ('índex de letalitat', 'Epidemiologia e Saúde Pública'),
 ('índex de mortalitat ', 'Epidemiologia e Saúde Pública'),
 ('óxido nítrico', 'Substâncias Químicas'),
 ('ús compassiu', 'Bioética e Leis')
]


# Converter para dicionário para busca rápida
conceito_para_categoria = dict(lista)

novo_glossario = []

for conceito in glossario:
    nome = conceito.get("Conceito")
    fontes = conceito.get("Fontes", {})
    categoria_encontrada = False
    for fonte_info in fontes.values():
        if 'Categoria' in fonte_info:
            categoria_encontrada = True
            break
    if not categoria_encontrada:
        # Se não tem categoria, tenta adicionar
        categoria = conceito_para_categoria.get(nome)
        if categoria:
            # Adiciona a categoria na primeira fonte existente
            if fontes:
                for fonte_info in fontes.values():
                    fonte_info['Categoria'] = categoria
                    break
            else:
                # Se não há fontes, cria uma fonte genérica
                conceito['Fontes'] = {'categoria_adicionada': {'Categoria': categoria}}
    novo_glossario.append(conceito)

# Salvar o novo JSON
with open('glossario_juncao_atualizado.json', 'w', encoding='utf-8') as f:
    json.dump(novo_glossario, f, ensure_ascii=False, indent=2)